{% set version = "1.0.11" %}
{% set posix = 'm2-' if win else '' %}
{% set native = 'm2w64-' if win else '' %}

package:
  name: r-ptxqc
  version: {{ version|replace("-", "_") }}

source:
  url:
    - {{ cran_mirror }}/src/contrib/PTXQC_{{ version }}.tar.gz
    - {{ cran_mirror }}/src/contrib/Archive/PTXQC/PTXQC_{{ version }}.tar.gz
  sha256: efcaf7e22220c816ebcac6d2af9bcbc53967ba162fabf07a77c4c12473ac0f97

build:
  merge_build_host: true  # [win]
  number: 0
  noarch: generic
  rpaths:
    - lib/R/lib/
    - lib/

requirements:
  build:
    - {{ posix }}zip               # [win]
  host:
    - r-base
    - r-rcolorbrewer
    - r-upsetr
    - r-data.table
    - r-ggdendro
    - r-ggplot2 >=2.2
    - r-gtable
    - r-jsonlite
    - r-kableextra
    - r-knitr >=1.10
    - r-ontologyindex
    - r-plyr
    - r-reshape2
    - r-rmarkdown
    - r-seqinr
    - r-yaml
  run:
    - r-base
    - r-rcolorbrewer
    - r-upsetr
    - r-data.table
    - r-ggdendro
    - r-ggplot2 >=2.2
    - r-gtable
    - r-jsonlite
    - r-kableextra
    - r-knitr >=1.10
    - r-ontologyindex
    - r-plyr
    - r-reshape2
    - r-rmarkdown
    - r-seqinr
    - r-yaml

test:
  commands:
    - $R -e "library('PTXQC')"           # [not win]
    - "\"%R%\" -e \"library('PTXQC')\""  # [win]

about:
  home: https://github.com/cbielow/PTXQC
  license: BSD-3-Clause
  summary: "Generates Proteomics (PTX) quality control (QC) reports for shotgun LC-MS data analyzed with the  MaxQuant software suite. Reports are customizable (target thresholds, subsetting) and available in HTML or PDF format. Published in J. Proteome Res., Proteomics Quality Control: Quality Control Software for MaxQuant\
    \ Results (2015) 'doi:10.1021/acs.jproteome.5b00780'."
  license_family: BSD
  license_file:
    - {{ environ["PREFIX"] }}/lib/R/share/licenses/BSD_3_clause

extra:
  recipe-maintainers:
    - conda-forge/r

# Package: PTXQC
# Type: Package
# Title: Quality Report Generation for MaxQuant Results
# Version: 0.92.6
# Date: 2019-04-16
# Author: Chris Bielow <chris.bielow@bsc.fu-berlin.de>
# Maintainer: Chris Bielow <chris.bielow@bsc.fu-berlin.de>
# Description: Generates Proteomics (PTX) quality control (QC) reports for shotgun LC-MS data analyzed with the  MaxQuant software suite. Reports are customizable (target thresholds, subsetting) and available in HTML or PDF format. Published in J. Proteome Res., Proteomics Quality Control: Quality Control Software for MaxQuant Results (2015) 'doi:10.1021/acs.jproteome.5b00780'.
# SystemRequirements: pandoc (http://pandoc.org) for building Vignettes and output reports as HTML
# Depends: R (>= 3.0.0)
# Imports: data.table, ggplot2 (>= 2.2), ggdendro, graphics, grid, gridExtra, grDevices, gtable, kableExtra, knitr (>= 1.10), methods, plyr, proto, RColorBrewer, reshape2, rmarkdown, seqinr, stats, utils, yaml
# Suggests: testthat
# VignetteBuilder: knitr
# License: GPL-2
# RoxygenNote: 6.1.1
# URL: https://github.com/cbielow/PTXQC
# BugReports: https://github.com/cbielow/PTXQC/issues
# NeedsCompilation: no
# Packaged: 2019-04-16 13:18:27 UTC; bielow
# Repository: CRAN
# Date/Publication: 2019-04-16 14:02:49 UTC
