travis:
  secure:
    BINSTAR_TOKEN: s4RBFVDUC1HvT4LP+N4cegZ238GDw/PmUWUI6WbkkDZ15Oqa5w4qLZj6BwJ8InAzwzbcO8xuJmWQdX68QqFOP8PFmDbHqATWbL1v6unHn9bhWDbevTxhxnJKpTAzMIiroNRVTNKt42rouztYmp9MDAvuAEPURU9P0uOgwQEecNFce6eGS6biVL/SalNF4lp7XhLMMPAnPL0PwJIYtvu/I6HN8Ner3UkO6QT6b42pK4kjhdqXpkioDiFDRm+70xoIYqER5oehBl0+DsB13oIpa3+qjGsOGZuzL/1AELvqq09f+08ATgnx/8ltAN8OVhZTzwjiHSSDVgxA5+y7y2tCH+n4VBmIdMtvAG9sYk64Yzz5reB3sOKDMceJRcYXHJMiUl7dqyGyD91VHCH6wr+eVWkA00VQ3l/TGHFXAaWWk9Bx/P52c7WTZowOz6tYWarqoxyACACssorSNy63R8RkMVW2JJR4SQvTxukIA8jdhmnyeA59EYq+GIDmRoJHWqpR/rf8THlSoP40Gn3N8vU2HhKJIzYYZJxAnHaRU/dum8LGBoCiggV+BEsgvUX3y0aGud/MGcfdSazwSYHPbfuf/CjNKuGgRJlK/CsZDOojI/+y3UX1xcsgdv+PVRbvIC9PoJhBgYCnK4aF1VtRsI4If6hSU+pvS0O3R7lYzZCg9rg=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
